<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Title>Buffering</Title>
        <Authors>Grovre</Authors>
        <Description>Efficient double buffering functionality for any system inspired by the DirectX swap chain</Description>
        <PackageProjectUrl>https://github.com/Grovre/Buffering</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Grovre/Buffering</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>buffering;double-buffering;swap-chain;concurrency;threading;lock;performance;aot</PackageTags>
        <PackageOutputPath>$(OutputPath)</PackageOutputPath>
        <Copyright>© 2026 Grovre</Copyright>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <Version>0.4.0</Version>
        <LangVersion>latestmajor</LangVersion>
        
        <PackageReleaseNotes>Heavily refactored the library to make usage as simple as possible and removed copy swap effect. Previously, a no-cost implementation allowed the double buffer to use all swap effects. However, flipping is much faster than copying, and copying isn't necessary as the user can track the variable the back buffer is pulling from. Removing copying also allowed serious simplification.</PackageReleaseNotes>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0|AnyCPU'">
      <IsAotCompatible>True</IsAotCompatible>
      <IsTrimmable>True</IsTrimmable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0|AnyCPU'">
      <IsAotCompatible>True</IsAotCompatible>
      <IsTrimmable>True</IsTrimmable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0|AnyCPU'">
      <IsAotCompatible>True</IsAotCompatible>
      <IsTrimmable>True</IsTrimmable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0|AnyCPU'">
      <IsAotCompatible>True</IsAotCompatible>
      <IsTrimmable>True</IsTrimmable>
    </PropertyGroup>
    
    <ItemGroup>
        <None Include="..\README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Testing" />
        <InternalsVisibleTo Include="Benchmarking" />
    </ItemGroup>

</Project>
